image:
  # -- image tag
  tag: 'latest'
  # -- image pull policy
  pullPolicy: Always

backup:
  enabled: false

env:
  NODE_ENV: production
  MONGODB_HOST: server-mongodb.fdj-ca.svc.cluster.local

persistence:
  media:
    size: 1Gi
