image:
  # -- image tag
  tag: 'latest-dev'
  # -- image pull policy
  pullPolicy: Always

backup:
  enabled: false

env:
  NODE_ENV: development
  MONGODB_HOST: server-mongodb.development.svc.cluster.local

persistence:
  media:
    size: 512Mi
