image:
  # -- image tag
  tag: 'latest-rc'
  # -- image pull policy
  pullPolicy: Always

ingressroute:
  routes:
    - host: fdj-ca-server.staging.outworld.fr
      priority: 10
      services:
        - passHostHeader: true
          name: server-fdj-ca-server
          port: 80

backup:
  enabled: false

env:
  NODE_ENV: staging

persistence:
  media:
    size: 512Mi
