image:
  # -- image tag
  tag: 'latest-rc'
  # -- image pull policy
  pullPolicy: Always

backup:
  enabled: false

env:
  NODE_ENV: staging
  MONGODB_HOST: server-mongodb.staging.svc.cluster.local

persistence:
  media:
    size: 512Mi
