image:
  # -- image tag
  tag: 'latest'
  # -- image pull policy
  pullPolicy: Always

ingressroute:
  routes:
    - host: fdj-ca-server.outworld.fr
      priority: 10
      services:
        - passHostHeader: true
          name: server-fdj-ca-server
          port: 80

backup:
  enabled: false

env:
  NODE_ENV: production

persistence:
  media:
    size: 1Gi
